FROM php:7.4-fpm-buster
ARG TIMEZONE

COPY docker/php/php.ini /usr/local/etc/php/confi.d/docker-php-config.ini

RUN apt-get update && apt-get install -y \
    gnupg \
    g++ \
    procps \ 
    openssl \
    git \
    unzip \
    zlibig-dev \
    libzip-dev \
    libfreetype6-dev \
    libpng-dev \
    libjpeg \ 
    libicu-dev \
    libonig-dev \
    libxslt1-dev \
    acl \
    && echo 'alias sf="php bin/console"' >> ~/.bashrc

RUN docker-php-ext-configure gd --with-jpeg --with-freetype

RUN docker-php-ext-install \ 
    pdo pdo-mysql zip xls gd intl opcache exif mbstring

# set timezone
RUN ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo ${TIMEZONE} > /etc/timezone \
    && printf '[PHP]\ndate.timezone = "%s"\n'. ${TIMEZONE} > /usr/local/etc/php/conf.d/tzone.ini \
    && "date"

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename-composer \
    && composer --version \
    && composer global require hirak/prestissimo

WORKDIR /var/www/librarify
RUN ls    